### ISSUE TITLE
SCON fails to encode large JS objects

### ISSUE THREAD

**Issue by ihatecsv** [BlueStone-Tech-Enterprises/scon#12]
Self explanatory. Using [this JSON generator](http://www.json-generator.com/) to make the objects, large JavaScript object inputs fail to encode with error:

```
RangeError: Index out of range
    at checkInt (buffer.js:1063:11)
    at Buffer.writeUInt16BE (buffer.js:1130:5)
    at Object.scon.writeKey (C:\Users\ThisUser\Desktop\testScon\node_modules\scon\lib\encode.js:22:7)
    at Object.scon.writeUInt (C:\Users\ThisUser\Desktop\testScon\node_modules\scon\lib\encode.js:119:17)
    at Object.scon.writeValue (C:\Users\ThisUser\Desktop\testScon\node_modules\scon\lib\encode.js:162:18)
    at C:\Users\ThisUser\Desktop\testScon\node_modules\scon\lib\encode.js:224:15
    at Array.forEach (native)
    at Object.scon.encode (C:\Users\ThisUser\Desktop\testScon\node_modules\scon\lib\encode.js:221:22)
    at Object.scon.writeValue (C:\Users\ThisUser\Desktop\testScon\node_modules\scon\lib\encode.js:185:19)
    at C:\Users\ThisUser\Desktop\testScon\node_modules\scon\lib\encode.js:224:15
```

Smaller objects encode fine.

**Comment by ihatecsv** [comment]
Example failing input JSON. This is a .json file, just change the extension. (Thanks GitHub, developers should totally not be allowed to upload .json files to comments, that's too dangerous.)

[input.txt](https://github.com/BlueStone-Tech-Enterprises/scon/files/1074391/input.txt)

**Comment by JamesxX** [comment]
Can you reproduce the error using the developer branch?

**Comment by ARitz-Cracker** [comment]
There are some underlying issues with the developer branch that have to be fixed.

**Comment by ARitz-Cracker** [comment]
Actually, I'm gonna change this to "won't fix" as I never plan to support veriable names longer than 65,535 bytes.
